### ISSUE TITLE
app_protect_security_log

### ISSUE THREAD

**Issue by dg410** [nginxinc/docker-nginx-controller#38]
Hi, we're not able to find app protect logs. 
The directive in nginx.conf is `app_protect_security_log /etc/controller-agent/configurator/auxfiles/log-default.json syslog:server=127.0.0.1:514;`. We want to find the logs containing app_protect_support_id, we've looked through all the logs in /var/log/app_protect, /var/log/nginx/access.log and docker logs.
We think the syslog configuration may be the problem, since we don't have syslog installed.
Thanks in advance.

**Comment by brianehlert** [comment]
The directive in the nginx.conf indicates that you using NGINX Controller with NAP and not using NAP stand alone.
Given this, the information you seek should be available through NGINX Controller.
The NGINX Controller agent should be capturing the log events and forwarding them to NGINX Controller.

**Comment by aknot242** [comment]
Once an application Component in NGINX Controller is configured with WAF enabled, Security Events will become visible in the Component area of the Controller UI. Each security event will have a Support ID associated with it. (see: [Security Events](https://docs.nginx.com/nginx-controller/services/app-delivery/security/tutorials/view-app-security-analytics/#view-app-security-events) )
