### ISSUE TITLE
Controller agent not sending component metrics to the controller

### ISSUE THREAD

**Issue by dg410** [nginxinc/docker-nginx-controller#47]
The Controller agent is not reporting component metrics and analytics viewed in the component page.
The avrd process uses the file /etc/controller-agent/metrics/config.json:
` avrd 2>&1 >/dev/null -m 64 --config /etc/controller-agent/metrics/config.json `
This directory /etc/controller-agent/metrics doesn't exist after the container is up and is registered to the controller.
After restarting the controller agent manually- killing the controller agent process ID and executing /usr/bin/nginx-controller-agent, the directory and file /etc/controller-agent/metrics/config.json exists, and there are component metrics.
We currently resolved this isuue by added a restart to the entrypoint after 30 second.

**Comment by brianehlert** [comment]
Is there a specific dockerfile example that you were using?
Such as a nap vs a non-nap example, or possibly a specific OS.

**Comment by dg410** [comment]
Hi, I'm using the centos nap docker file

**Comment by brianehlert** [comment]
Thank you for that additional detail.
We have someone looking into this.

**Comment by dg410** [comment]
Worked, thanks!
