### ISSUE TITLE
Security log not found

### ISSUE THREAD

**Issue by RoeiGanor** [nginxinc/docker-nginx-controller#60]
Im using centos with nap enabled instance using agent version 3.17.
In /etc/controller-agent/agent.conf under [extensions] there is security = True but when the waf reject a request i cant see it in /var/log/nginx-controller/security-events-mgr.log (where it usually exists).
The events are not shown up in the controller although the WAF metrics do exists.
This bug was also with 3.12 and the update to 3.17 didn't solved it, i also tried to delete the container and deploy it from scratch but with no luck.

Im kinda lost and wish you could help me.

**Comment by aknot242** [comment]
The /var/log/nginx-controller/security-events-mgr.log is used for troubleshooting, not for identifying WAF security events from an administrative perspective. As regards “events are not showing up in the controller” - the obvious things to check: are there any errors in /var/log/nginx-controller/security-events-mgr.log? The security events themselves should be flowing to the Controller App Security UI under normal circumstances. If this is not happening, it needs to be examined further.

**Comment by RoeiGanor** [comment]
In this log there info log after initialization but after the init nothing is being written

**Comment by aknot242** [comment]
The WAF log messages should be sent to Controller and viewable there. Can we connect directly to resolve your issue over email or Zoom? You can contact NGINX support, or contact me directly and I can get you connected with the right engineers to help resolve your issue. 

Daniel Edgar
edgar@f5.com
